name       : python-language-server
version    : 0.36.1
release    : 3
source     :
    - https://github.com/palantir/python-language-server/archive/0.36.1.tar.gz : 7320643efb01be8956557cead3d46e782d6db4e3ca351bb659d09c00bd70c44a
homepage   : https://github.com/palantir/python-language-server
license    : MIT
component  : programming.python
summary    : An implementation of the Language Server Protocol for Python
description: |
    An implementation of the Language Server Protocol for Python
builddeps  :
    - autopep8
    - flake8
    - matplotlib
    - pydocstyle
    - pyflakes
    - pylint
    - python-flaky
    - python-jsonrpc-server
    - python-mock
    - python-pandas
    - python-pytest-cov
    - python-rope
    - python3-jedi
    - python3-qt5
    - yapf
rundeps    :
    - python-jsonrpc-server
    - python-pluggy
    - python3-jedi
    - yapf
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
