name       : python-language-server
version    : 0.36.2
release    : 8
source     :
    - https://github.com/palantir/python-language-server/archive/0.36.2.tar.gz : fb573f780467c1cae0de47065eecbaaf9b457bd5cbe9f5cf8409224e1cd21cf6
homepage   : https://github.com/palantir/python-language-server
license    : MIT
component  : programming.python
summary    : An implementation of the Language Server Protocol for Python
description: |
    An implementation of the Language Server Protocol for Python
builddeps  :
    - autopep8
    - flake8
    - matplotlib
    - pydocstyle
    - pylint
    - python-flaky
    - python-jsonrpc-server
    - python-mock
    - python-pandas
    - python-pytest-cov
    - python-rope
    - python3-jedi
    - python3-qt5
    - yapf
rundeps    :
    - autopep8
    - flake8
    - pydocstyle
    - python-jsonrpc-server
    - python-pluggy
    - python-typing-extensions
    - python3-jedi
    - yapf
setup      : |
    sed -i 's/pycodestyle<2.7.0,/pycodestyle/g' setup.py
    sed -i 's/pyflakes<2.3.0,/pyflakes/g' setup.py
    sed -i 's/pycodestyle>=2.6.0,<2.7.0/pycodestyle>=2.6.0/g' setup.py
    sed -i 's/pyflakes>=2.2.0,<2.3.0/pyflakes>=2.2.0/g' setup.py
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    #python3_test pytest3 -v -k 'not test_flake8_lint.py'
