name       : python-language-server
version    : 0.36.1
release    : 4
source     :
    - https://github.com/palantir/python-language-server/archive/0.36.1.tar.gz : e7bf10efed9dad2f6c0d6c0b77b066006ba2ea652eab1330a02296110bac395a
homepage   : https://github.com/palantir/python-language-server
license    : MIT
component  : programming.python
summary    : An implementation of the Language Server Protocol for Python
description: |
    An implementation of the Language Server Protocol for Python
builddeps  :
    - autopep8
    - flake8
    - matplotlib
    - pydocstyle
    - pyflakes
    - pylint
    - python-flaky
    - python-jsonrpc-server
    - python-mock
    - python-pandas
    - python-pytest-cov
    - python-rope
    - python3-jedi
    - python3-qt5
    - yapf
rundeps    :
    - python-jsonrpc-server
    - python-pluggy
    - python3-jedi
    - yapf
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
